# Generated by Django 5.0.7 on 2024-07-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_book_publishdate_book_publishingcountry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
